name = "pan-website-prototype"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
output_dir = "dist"

[env.production]
name = "pan-website-prototype"

[env.preview]
name = "pan-website-prototype-preview"
